### ISSUE TITLE
Unable to complete request. Got 404 when image name has _ (underscore)

### ISSUE THREAD

**Issue by pulpo** [deepfence/package-scanner#25]
I'm trying to scan images into a private ECR, I've no problem to scan some images, but another ones are giving me the following error

```
deepfence-package-scanner-******* deepfence-package-scanner time="XXXXX" level=error msg="*******.dkr.ecr.us-east-1.amazonaws.com/xxx/k8s/some_image:v1.1.1-10_2022-09-14T17:42:02.000 Unable to complete request. Got 404 "
```
After searching for a pattern on the fail, I found that all the images that has an underscore at the name, are giving errors. 

This later reports to deepfence-vulnerabilty-mapper as a `unexpected end of JSON input`

```
deepfence-vulnerability-mapper-******* deepfence-vulnerability-mapper time="XXXXX" level=error msg="unexpected end of JSON input"
``` 
According to [ECR documentation](https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-create.html) underscore names are allowed at the registry.

**Comment by ibreakthecloud** [comment]
Hi @pulpo, how are you triggering the build? I tried with these images in ECR Private repo, seems to be passing:

<img width="1446" alt="image" src="https://user-images.githubusercontent.com/18168330/190952178-5bf2f94f-58c0-423d-ad48-886bfbb5328a.png">


logs
```
deepfence-vulnerability-mapper  | time="2022-09-19 04:53:12" level=info msg="Scan completed for image: *(************.dkr.ecr.us-east-1.amazonaws.com/under_score_test:with_underscore"
```

**Comment by pulpo** [comment]
I'm launching it via the UI (with the Action check)... I'll perform a new test with some images and will be back to you.

**Comment by pulpo** [comment]
Well, seems to be something related to the structure of the image (I tried to move one of the failing image to another registry, without underscores on it), changed the tag, and the 404 problem repeats..  correlation does not imply causation at least for this case.. thanks @ibreakthecloud for the effort.

**Comment by ibreakthecloud** [comment]
> Well, seems to be something related to the structure of the image (I tried to move one of the failing image to another registry, without underscores on it), changed the tag, and the 404 problem repeats.. correlation does not imply causation at least for this case.. thanks @ibreakthecloud for the effort.

Happy to help @pulpo . Would it be possible to know what image is that, or is it publicly available?

**Comment by pulpo** [comment]
Is not a public image, let me see if I can reproduce the same fault with one without business code, so we can analyze it together.

**Comment by ibreakthecloud** [comment]
> Is not a public image, let me see if I can reproduce the same fault with one without business code, so we can analyze it together.

sounds good! thanks.
